export const languagesOptions = [
  "English",
  "English (Australia)",
  "English (Canada)",
  "English (India)",
  "English (New Zealand)",
  "English (South Africa)",
  "English (United Kingdom)",
  "English (United States)",
  "Central Kurdish - کوردی (دەستنوسی عەرەبی)",
  "Chinese - 中文",
  "Chinese (Hong Kong) - 中文（香港）",
  "Chinese (Simplified) - 中文（简体）",
  "Chinese (Traditional) - 中文（繁體）",
  "French - français",
  "French (Canada) - français (Canada)",
  "French (France) - français (France)",
  "French (Switzerland) - français (Suisse)",
  "German (Austria) - Deutsch (Österreich)",
  "Hebrew - עברית",
  "Hindi - हिन्दी",
  "Italian (Italy) - italiano (Italia)",
  "Japanese - 日本語",
  "Lao - ລາວ",
  "Latin",
  "Mongolian - монгол",
  "Portuguese - português",
  "Portuguese (Brazil) - português (Brasil)",
  "Portuguese (Portugal) - português (Portugal)",
  "Spanish - español",
  "Spanish (Mexico) - español (México)",
  "Spanish (Spain) - español (España)",
  "Spanish (United States) - español (Estados Unidos)",
  "Swahili - Kiswahili",
  "Xhosa",
  "Zulu - isiZulu",
];
